# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Clona o repositório e seus submódulos para o contexto de build
    - name: Checkout repository
      uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
    - name: Generate files
      run: npx github-contribution-grid-snake -u SousaDev97 -o output

    # Move os arquivos gerados para um diretório específico
    - name: Move files
      run: |
        mv ./output/github-contribution-grid-snake.gif ./output/assets/github-contribution-grid-snake.gif
        mv ./output/github-contribution-grid-snake.svg ./output/assets/github-contribution-grid-snake.svg

    # Configuração do Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Commit das alterações
    - name: Commit Changes
      run: |
        git add .
        git commit -m "Atualizar contribuição do GitHub"
        git push origin main

    # Criação do branch de saída (output)
    - name: Create Output Branch
      run: |
        git checkout --orphan output
        git rm -rf .
        cp -R output/* .
        touch .nojekyll
        git add .
        git commit -m "Initial commit"
        git push -f origin output
