# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: SousaDev97 #Seu usuario
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    - run: git status

    # Configuração do Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Commit das alterações
    - name: Commit Changes
      run: |
        git add .
        git commit -m "Atualizar contribuição do GitHub"
        git branch -m main
        git push origin main

    # Criação do branch de saída (output)
    - name: Create Output Branch
      run: |
        git checkout --orphan output
        git rm -rf .
        mv dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.gif.png
        mv dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.svg.png
        mv dist/ dist/assets/
        touch .nojekyll
        git add .
        git commit -m "Initial commit"
        git push -f origin output
